version: '1.0.0'
services:
  frontend:
    container_name: frontend
    env_file:
      - .env
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    environment:
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      CHOKIDAR_USEPOLLING: true
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    volumes:
      - ./packages/frontend:/Seven/packages/frontend
      - ./packages/frontend/node_modules:/Seven/packages/frontend/node_modules
    stdin_open: true
    tty: true

  backend:
    container_name: backend
    ports:
      - 8000:8000
    env_file:
      - .env
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    volumes:
    - ./packages/backend:/Seven/packages/backend
    - ./packages/backend/node_modules:/Seven/packages/backend